version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.7.2
      - pg_image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: sweater_weather_development
    environment:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      PGHOST: 127.0.0.1
      PGUSER: postgres
      RAILS_ENV: development
    executor: ruby/default
    steps:
      - checkout
      - run: cp config/database.yml.ci config/database.yml
      - run:
          name: Bundler Version
          command: bundle -v
      - run:
        name: Build Gemfile
        command: bundle install
      - run:
        name: Setup DB
        command: bundle exec rails db:schema:load --trace
      - run:
        name: Run Test Suite
        command: bundle exec rspec

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample:
    jobs:
      - build
